blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('<int:post_id>/add_comment', views.add_comment, name='add_comment')
]

blogify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Roboczy'
        PUBLISHED = 'PB', 'Opublikowany'

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    object = models.Manager()
    published = PublishManager()

    # Klasa która odwraca kolejność wpisów
    class Meta:
        ordering = ['-publish']
        # indeksacja w bazie
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    # metoda która tworzy kanoniczny adres URL
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    nick = models.CharField(max_length=30)
    content = models.CharField(max_length=1000)
    create = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,
                               null=True,
                               default=None,
                               blank=True,
                               related_name='comments',
                               on_delete=models.CASCADE)
    post = models.ForeignKey(Post,
                             related_name='comments',
                             on_delete=models.CASCADE)

blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.Form):
    nick = forms.CharField(min_length=3, max_length=30, required=True)
    content = forms.CharField(min_length=10, max_length=1000, required=True, widget=forms.Textarea)

blog/views.py
import sys

from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail  # importujemy biblioteke która wyśle maila
from django.contrib import messages


def post_list(request):
    posts = Post.published.all()
    # Dodanie stronnicowania/paginacji z 3 postami na stronę
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    # obsługa stron wykraczających poza zakres
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        # jeśli zmienna page_number jest poza zakresem to wyświetl ostatnią stronę wyników
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        # jeśli zmienna page_number nie jest liczbą to wyświetl pierwszą stronę wyników
        posts = paginator.page(1)

    return render(request,
                  'post/list.html',
                  {'posts': posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.all()
    comment_form = CommentForm()

    if request.user.is_authenticated:
        comment_form.fields['nick'].disabled = True
        comment_form.fields['nick'].initial = request.user.username

    return render(request,
                  'post/detail.html',
                  {'post': post, 'comment_form': comment_form, 'comments': comments})


def add_comment(request, post_id):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             pk=post_id)
    author = None
    nick = request.POST.get('nick')

    if request.user.is_authenticated:
        nick = request.user.username
        author = request.user

    form = CommentForm({'content': request.POST.get('content'), 'nick': nick})

    if form.is_valid():
        cd = form.cleaned_data
        comment = Comment(nick=cd['nick'], content=cd['content'], author=author, post=post)
        comment.save()
        messages.add_message(request, messages.SUCCESS, "Pomyślnie dodano komentarz")
    else:
        messages.add_message(request, messages.ERROR, "Wystąpiły błędy przy dodawaniu komentarza")
    return redirect(post.get_absolute_url())


# metoda osbługująca egzemplarz formularza i jego przesyłanie

def post_share(request, post_id):
    # Pobieramy post według identyfikatora
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':  # POST to nie nazwa posta/artykułu ale metody przesyłania danych z formularzy
        # Formularz został przesłąny
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Pomyślnie zweryfikowano poprawność pól formularza
            cd = form.cleaned_data
            # określamy jak ma wyglądać wiadomość
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} polecam Ci przeczytanie {post.title}'
            massage = f'Przeczytaj {post.title} pod adresem {post_url} \n Mój komentarz do artukułu: {cd["comments"]}'
            send_mail(subject, massage,
                      'kamil.nowak.testuj@gmail.com',
                      [cd['to']])
            sent = True  # zmiana flagi na wiadomość wysłaną
            # ... wysyłanie maila
    else:
        form = EmailPostForm()

    return render(request,
                  'post/share.html',
                  {'post': post, 'form': form, 'sent': sent})

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href='{% static "blog.css" %}' rel="stylesheet">
</head>
<body>
  <div id="content">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog.</p>
  </div>
</body>
</html>

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
    {% endif %}
    <span class="current">
      Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Następna</a>
    {% endif %}
  </span>
</div>

blog/templates/post/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Opublikowany {{ post.publish }} przez {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href='{% url "blog:post_share" post.id %}'>
      Chcesz udostępnić ten post?
  </a>

  <h4>Lista komentarzy</h4>
  <div class="comments-list">
  {% if post.comments.count > 0 %}
    {% for comment in comments %}
      <div class="comment">
          <p class="info">
            Opublikowany {{ post.create }} przez {{ post.nick }}
          </p>
          <p class="content">
            {{ comment.content }}
          </p>
      </div>
    {% endfor %}
  {% else %}
    <p>Brak komentarzy.</p>
  {% endif %}
  </div>

  <h4>Dodaj komentarz</h4>
  <div>
    <form method="post" action="{% url 'blog:add_comment' post_id=post.id %}">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Dodaj komentarz">
    </form>
    <br class="clear" />
  </div>
  <a href="{% url 'blog:post_list' %}">&lt; powrót</a>
{% endblock %}

blog/templates/post/list.html
{% extends "base.html" %}

{% block title %}Mój blog{% endblock %}

{% block content %}
    <h1>Mój blog</h1>
    {% for post in posts %}
        <h2>
            <a href='{{ post.get_absolute_url }}'>
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Opublikowany {{ post.publish }} przez {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    <!--    dodajemy plik pagination.html-->
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/post/share.html
{% extends "base.html" %}

{% block title %} Udostępnij post {% endblock%}

{% block content %}
    <div>
    {% if sent %}
        <h1>Wiadomość e-mail została wysłana pomyślnie</h1>
        <p>
            Wysłanie posta {{post.title}} do {{form.cleaned_date.to}}
            zakończyło się sukcesem.
        </p>
    {% else %}
        <h1>Udostępnij "{{post.title}}" przez maila</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Wyślij wiadomość e-mail">
        </form>
    {% endif %}
        <br class="clear" />
    </div>
    <a href="{{ post.get_absolute_url }}">&lt; powrót</a>
{% endblock %}